apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  selector:
    # app: istio-gateway
    istio: gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 3306
      name: mysql
      protocol: TCP
    hosts:
    - "db.quickdrawai.net"
  - port:
      number: 6379
      name: redis
      protocol: TCP
    hosts:
    - "db.quickdrawai.net"
  - port:
      number: 9200
      name: opensearch
      protocol: TCP
    hosts:
    - "db.quickdrawai.net"
  - port:
      number: 5601
      name: opensearch-dashboard
      protocol: TCP
    hosts:
    - "db.quickdrawai.net"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-redis
  namespace: redis
spec:
  hosts:
  - 'db.quickdrawai.net'
  gateways:
  - istio-system/istio-gateway
  - mesh # applies to all the sidecars in the mesh
  tcp:
  - match:
    - port: 6379
    route:
    - destination:
        host: redis-headless.redis.svc.cluster.local
        port:
          number: 6379
  # http:
  # - match:
  #   # - headers:
  #   #     cookie:
  #   #       regex: "^(.*?;)?(user=dev-123)(;.*)?"
  #   - uri:
  #       prefix: /opensearch/
  #   - uri:
  #       prefix: /opensearch
  #   rewrite:
  #     uri: "/"
  #   route:
  #   - destination:
  #       port:
  #         number: 9200
  #       host: fastapi-demo.default.svc.cluster.local
