calicoctl create -f - <<EOF
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  serviceClusterIPs:
  # - cidr: 10.96.0.0/12
  # - cidr: 192.168.0.0/16
  # - cidr: fd00:1234::/112
  # serviceExternalIPs:
  # # - cidr: 192.168.0.0/16
  # - cidr: 10.250.107.189/32
  # - cidr: 10.250.107.191/32
  # - cidr: 10.250.107.192/32
  # - cidr: 10.250.107.193/32
  # - cidr: 10.250.107.194/32
  serviceLoadBalancerIPs:
  - cidr: 10.250.107.189/32
  nodeToNodeMeshEnabled: true
EOF

# calicoctl delete -f - <<EOF
# apiVersion: projectcalico.org/v3
# kind: BGPPeer
# metadata:
#   name: my-global-peer
# spec:
#   peerIP: 192.168.30.40
#   asNumber: 64567
# EOF