apiVersion: v1
kind: PersistentVolume
metadata:
  name: opensearch-cluster-master
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadOnlyMany
  storageClassName: manual
  hostPath:
    path: /volume/opensearch
    # path: "/data/kind_host_volume"
