apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-cluster-master
  namespace: opensearch
spec:
  volumeName: opensearch-cluster-master
  storageClassName: manual
  accessModes:
    - ReadOnlyMany  # access mode 
  resources:
    requests:
      storage: 300Gi