apiVersion: v1
kind: PersistentVolume
metadata:
  name: qdrant-storage
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  storageClassName: manual
  hostPath:
    path: /var/tmp/kind_volume/qdrant
    # path: "/data/kind_host_volume"
