apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-storage
  namespace: qdrant
spec:
  volumeName: qdrant-storage
  storageClassName: manual
  accessModes:
    - ReadOnlyMany  # access mode 
  resources:
    requests:
      storage: 100Gi