apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql
  labels:
    app: postgresql
    app/group: corus
    app/profile: default
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: codev-nfs-storageclass
  claimRef:
    namespace: postgresql
    name: postgresql
  nfs:
    server: 10.250.107.189
    path: /mnt/shared/db
    readOnly: false
