apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: postgresql
  labels:
    app: postgresql
    app/group: corus
    app/profile: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "codev-nfs-storageclass"
  volumeMode: Filesystem
  volumeName: postgresql
  resources:
    requests:
      storage: 100Gi