kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    apiVersion: kubelet.config.k8s.io/v1beta1
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: cpu=6,memory=12Gi
  extraPortMappings:
  - containerPort: 30000
    hostPort: 80
    listenAddress: "127.0.0.1"
    protocol: TCP
  extraMounts:
    - hostPath: /private/tmp/volumes
      containerPath: /volumes
      # readOnly: true
    - hostPath: "$HOME/.ssl"
      containerPath: /usr/local/share/ca-certificates
      # readOnly: true
# - role: worker