apiVersion: v1
kind: Secret
metadata:
    name: az-domain-cert
    namespace: opensearch
    labels:
        app/group: corus
type: Opaque
stringData:
    pemtrustedcas.pem: |
        -----BEGIN CERTIFICATE-----
        MIIDxTCCAq2gAwIBAgIBADANBgkqhkiG9w0BAQsFADCBgzELMAkGA1UEBhMCVVMx
        EDAOBgNVBAgTB0FyaXpvbmExEzARBgNVBAcTClNjb3R0c2RhbGUxGjAYBgNVBAoT
        EUdvRGFkZHkuY29tLCBJbmMuMTEwLwYDVQQDEyhHbyBEYWRkeSBSb290IENlcnRp
        ZmljYXRlIEF1dGhvcml0eSAtIEcyMB4XDTA5MDkwMTAwMDAwMFoXDTM3MTIzMTIz
        NTk1OVowgYMxCzAJBgNVBAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQH
        EwpTY290dHNkYWxlMRowGAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjExMC8GA1UE
        AxMoR28gRGFkZHkgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkgLSBHMjCCASIw
        DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL9xYgjx+lk09xvJGKP3gElY6SKD
        E6bFIEMBO4Tx5oVJnyfq9oQbTqC023CYxzIBsQU+B07u9PpPL1kwIuerGVZr4oAH
        /PMWdYA5UXvl+TW2dE6pjYIT5LY/qQOD+qK+ihVqf94Lw7YZFAXK6sOoBJQ7Rnwy
        DfMAZiLIjWltNowRGLfTshxgtDj6AozO091GB94KPutdfMh8+7ArU6SSYmlRJQVh
        GkSBjCypQ5Yj36w6gZoOKcUcqeldHraenjAKOc7xiID7S13MMuyFYkMlNAJWJwGR
        tDtwKj9useiciAF9n9T521NtYJ2/LOdYq7hfRvzOxBsDPAnrSTFcaUaz4EcCAwEA
        AaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYE
        FDqahQcQZyi27/a9BUFuIMGU2g/eMA0GCSqGSIb3DQEBCwUAA4IBAQCZ21151fmX
        WWcDYfF+OwYxdS2hII5PZYe096acvNjpL9DbWu7PdIxztDhC2gV7+AJ1uP2lsdeu
        9tfeE8tTEH6KRtGX+rcuKxGrkLAngPnon1rpN5+r5N9ss4UXnT3ZJE95kTXWXwTr
        gIOrmgIttRD02JDHBHNA7XIloKmf7J6raBKZV8aPEjoJpL1E/QYVN8Gb5DKj7Tjo
        2GTzLH4U/ALqn83/B2gX2yKQOC16jdFU8WnjXzPKej17CuPKf1855eJ1usV2GDPO
        LPAvTK33sefOT6jEm0pUBsV/fdUID+Ic/n4XuKxe9tQWskMJDE32p2u0mYRlynqI
        4uJEvlz36hz1
        -----END CERTIFICATE-----

    pemcert.pem: |
        -----BEGIN CERTIFICATE-----
        MIIGmTCCBYGgAwIBAgIJAPfzIEVXg+GYMA0GCSqGSIb3DQEBCwUAMIG0MQswCQYD
        VQQGEwJVUzEQMA4GA1UECBMHQXJpem9uYTETMBEGA1UEBxMKU2NvdHRzZGFsZTEa
        MBgGA1UEChMRR29EYWRkeS5jb20sIEluYy4xLTArBgNVBAsTJGh0dHA6Ly9jZXJ0
        cy5nb2RhZGR5LmNvbS9yZXBvc2l0b3J5LzEzMDEGA1UEAxMqR28gRGFkZHkgU2Vj
        dXJlIENlcnRpZmljYXRlIEF1dGhvcml0eSAtIEcyMB4XDTIzMDYyMDA4MTY1M1oX
        DTI0MDYyMDA4MTY1M1owHDEaMBgGA1UEAwwRKi5xdWlja2RyYXdhaS5uZXQwggEi
        MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDRhNBewfihlpjIFLYjPAhOhxWD
        NnR6qWyU7X5pIXQ72QYrHlvo2/iM4cH6xJk44TyWg85DpNycqCdodCQGFYYe8HAs
        O4lmPbjS2GYJ2QzdZyn2Zj2vYq7tJgCdcQnV3AOAsoD4omOqI6vJHDwTLlAxyFoC
        8fTaAuae7kBnFwuc2xDURgHYHt+fVVQeeJRG7eLG6b60EjV3+8hZJWsRj2wY5Idl
        55IE0ymF/dvyoEUEYtxC8zwsh2Gt+YW4LRAon9igj9XvJ+MmULU1KL8A90pwLwsB
        AiyjpsZIGZ1AorHyUUu5d3YgkZOb5uNTtIjBmCMhqhwQCiT8oc3K83aQNpz5AgMB
        AAGjggNDMIIDPzAMBgNVHRMBAf8EAjAAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggr
        BgEFBQcDAjAOBgNVHQ8BAf8EBAMCBaAwOAYDVR0fBDEwLzAtoCugKYYnaHR0cDov
        L2NybC5nb2RhZGR5LmNvbS9nZGlnMnMxLTYzMjkuY3JsMF0GA1UdIARWMFQwSAYL
        YIZIAYb9bQEHFwEwOTA3BggrBgEFBQcCARYraHR0cDovL2NlcnRpZmljYXRlcy5n
        b2RhZGR5LmNvbS9yZXBvc2l0b3J5LzAIBgZngQwBAgEwdgYIKwYBBQUHAQEEajBo
        MCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5nb2RhZGR5LmNvbS8wQAYIKwYBBQUH
        MAKGNGh0dHA6Ly9jZXJ0aWZpY2F0ZXMuZ29kYWRkeS5jb20vcmVwb3NpdG9yeS9n
        ZGlnMi5jcnQwHwYDVR0jBBgwFoAUQMK9J47MNIMwojPX+2yz8LQsgM4wLQYDVR0R
        BCYwJIIRKi5xdWlja2RyYXdhaS5uZXSCD3F1aWNrZHJhd2FpLm5ldDAdBgNVHQ4E
        FgQU6fMP3ow8oY0X6Qa8mDXJufNA0HQwggF+BgorBgEEAdZ5AgQCBIIBbgSCAWoB
        aAB2AO7N0GTV2xrOxVy3nbTNE6Iyh0Z8vOzew1FIWUZxH7WbAAABiNfgzswAAAQD
        AEcwRQIhAPofXoHiab5Yk+qcOPsOtcPYY2CVgr3DRQ4YXPBnZ0C6AiBNah6vI3a9
        yzBfto3s2oT/+/t5C4zfBMWd2iI7/zdMugB2AEiw42vapkc0D+VqAvqdMOscUgHL
        Vt0sgdm7v6s52IRzAAABiNfgz5wAAAQDAEcwRQIgRlw3n3Z8UcixxxokWdDqL0Ed
        zmWIu59kAjsYnS+qsf8CIQDt0ox28x17BHyN0z5y2VoztLyEprSLx48kehWEuXgP
        5QB2ANq2v2s/tbYin5vCu1xr6HCRcWy7UYSFNL2kPTBI1/urAAABiNfg0AEAAAQD
        AEcwRQIgQrA0hpSioVm1sInD0p9fg1A4ZupVwzayoZaBN+cCaZ0CIQDY9hIE2glp
        2Y0Ru/4Vhv8awQDUOsbmkHEEqfzVRGCuczANBgkqhkiG9w0BAQsFAAOCAQEAozh3
        tE1EYqW+ZcwWOkuTj6en0cxkAQjumaxFZe/5wbnJ9fZj6ynquvCfTjpAyDstwFhf
        uwBsuHTJ9pXtVEfwgC+K+42XcJhqg/tVQwaz+RcURjqVg47i6m2/J70FFLsoJSKt
        c8+BxF7OWOVuVzdBDZLqt/XC5zhI8uduWGykSMQqVhVhVqD1SRn/wR5DcnTx4oa4
        beJZ0+foeCJnmQJjBogFayl90DQn0gJaedcuoimuBD7Sam1ZaJMF7/WZQJsDnxPB
        z5ZWikl6cgSQXJ/YLD5EnyCkXFsoBuqeNoTVQFOuoeT4cFtpi2UiVrqezrIJmNSq
        qBd3IKsV8STspKhUBg==
        -----END CERTIFICATE-----

    pemkey.pem: |
        -----BEGIN PRIVATE KEY-----
        MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDRhNBewfihlpjI
        FLYjPAhOhxWDNnR6qWyU7X5pIXQ72QYrHlvo2/iM4cH6xJk44TyWg85DpNycqCdo
        dCQGFYYe8HAsO4lmPbjS2GYJ2QzdZyn2Zj2vYq7tJgCdcQnV3AOAsoD4omOqI6vJ
        HDwTLlAxyFoC8fTaAuae7kBnFwuc2xDURgHYHt+fVVQeeJRG7eLG6b60EjV3+8hZ
        JWsRj2wY5Idl55IE0ymF/dvyoEUEYtxC8zwsh2Gt+YW4LRAon9igj9XvJ+MmULU1
        KL8A90pwLwsBAiyjpsZIGZ1AorHyUUu5d3YgkZOb5uNTtIjBmCMhqhwQCiT8oc3K
        83aQNpz5AgMBAAECggEBAM3Nzzv0/vwCyMpohcywcFxqlngP6nR+rbjQXIZ6JQmQ
        kV2TcaaXRFtmeruPmA5mOLSEffy2GToMdsFErAoJ5HfJp/Xa+YkjgcQiaoCr4tYs
        Ouzc2yTHI5qw5JPCcG3QsuQc81DHemyqo1hl0qDosj9kVP5lmyT3Cn/8+egJnA+S
        3MVtoxqc29gQSBizxHBTE/q2D15KmXQN5/sLrxTRYdK84OsE5dX36v0UWGjHVod8
        tpYrpmS/YRqBV4CY0z4kKtwFvu8efoF5q1Me5QSRi2gusaKY1fSkdRfV8upTTCo6
        qEoa5LzNYBDiedfbHFOlPJ4MzYd25QLinMj/ltprYj0CgYEA52eF3BPnUzPMidA0
        okU44HozpQ2egN/Hg5x+DwLKVFA/AW0pgjenuUw0Ze1HR2ma+D18E2D9qUSXhZ1b
        yJZu88a2pD4Zatha/8oiofVbanPTGxENRactAKLeu1rUiGPYIuENUuLZPJCJ1WSn
        V3bym0NR20k8on3cFyG/sQJlk/MCgYEA58nJrXRVTOSBSRxcw2tVhvibo5CQeVG6
        SX9KZ1yIS2msGSI/euDqO4zmDTHR7snCtXJbxQOeR83N+9FwKk1855H9tFCWisnR
        P0JdgDjt2MPiuGG2VKlkkLv5/+SQUZiH82hNgpFYe3Iw2bv8pxkpjFNFG13gOebE
        uoYcQAc/gmMCgYEAtTAe5PKEt2YgqmvnOoO/BC1LENq4GCqgOtIm9jP2HsxyePhz
        fu17G6CqioCexjDPUb46z6WrGIWHquxKeKYpnCEk0zd4iWt83Tn1oiDOgmzMiC3y
        2W4L06qzgbmeHmknTDAxUYwkEsMN2ZOlX9vYHHA6wNv4aTbpRQd84+l/hbcCgYEA
        zlSnbfuHz0n9+HoB7YeHe/2kdmbC5OwmuzRPpFEPlqn7o+gDwDuk5tvXEdnOehUq
        eWDSZj+BT4PZoBdhFJcj3/Pqdu/iAqwC06AdIX4L5BEDqoR4zUZ5GgnrUqpA+hGg
        u8GWdesya7lL2RbpoknY3WxmsSTQ7FoLt8qYLTsGgucCgYACIOEVtHe+h8HoOEeP
        f64E+1b3qwYL8fZgYp7SiHNuSEFU5WZHbjU/Fz7lNj7vo+qQYWU2zEuNZQ61YR4R
        2pZR/c2piAxcICW9n5weDKeF+6kq+X6l8J1vhpTawT1zHUCG8vmzpA/Nw3AhrKOQ
        BXdubtQxCCXXSdlNQWe62tftyw==
        -----END PRIVATE KEY-----
