apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  storageClassName: manual
  hostPath:
    path: /var/tmp/kind_volume/postgresql
    # path: "/data/kind_host_volume"
