apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: postgresql
spec:
  volumeName: postgresql
  storageClassName: manual
  accessModes:
    - ReadOnlyMany  # access mode 
  resources:
    requests:
      storage: 100Gi