apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: tigera-operator
  namespace: {{.Release.Namespace}}
imagePullSecrets: {{- include "tigera-operator.imagePullSecrets" . | nindent 2 }}
