apiVersion: v1
kind: PersistentVolume
metadata:
  name: corus-file-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  storageClassName: manual
  hostPath:
    path: "/tmp/volumes"