apiVersion: v1
kind: PersistentVolume
metadata:
  name: corus-file-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  storageClassName: manual
  hostPath:
<<<<<<< Updated upstream
    path: /volume
    # path: "/data/kind_host_volume"
=======
    #path: "/data/kind_host_volume"
    path: "/volume"
>>>>>>> Stashed changes
