apiVersion: v1
kind: ServiceAccount
metadata:
  name: corus
  namespace: corus
  labels:
    app/group: corus
imagePullSecrets:
- name: az-ecr-cred
---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   # "namespace" omitted since ClusterRoles are not namespaced
#   name: corus-admin
# rules:
# - apiGroups: 
#   - ""
#   #
#   # at the HTTP level, the name of the resource for accessing Secret
#   # objects is "secrets"
#   resources: 
#   - "*"
#   verbs: 
#   - "*"
#   - "get"
#   - "watch"
#   - "list"
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# # This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
# kind: ClusterRoleBinding
# metadata:
#   name: corus-admin
# subjects:
# # - kind: Group
# #   name: system:serviceaccounts
# #   apiGroup: rbac.authorization.k8s.io
# #   namespace: corus
# - kind: ServiceAccount
#   name: corus # Name is case sensitive
#   namespace: corus
# roleRef:
#   kind: ClusterRole
#   name: corus-admin
#   apiGroup: rbac.authorization.k8s.io
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# # This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
# kind: ClusterRoleBinding
# metadata:
#   name: corus-cluster-admin
# subjects:
# # - kind: Group
# #   name: system:serviceaccounts
# #   apiGroup: rbac.authorization.k8s.io
# #   namespace: corus
# - kind: ServiceAccount
#   name: corus # Name is case sensitive
#   namespace: corus
# roleRef:
#   kind: ClusterRole
#   name: cluster-admin
#   apiGroup: rbac.authorization.k8s.io
