apiVersion: v1
kind: PersistentVolume
metadata:
  name: corus-file-storage
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  storageClassName: manual
  hostPath:
    # path: /volume
    path: /var/tmp/kind_volume/corus-file-storage
