apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: corus-file-storage-claim
  namespace: corus
spec:
  volumeName: corus-file-storage
  storageClassName: manual
  accessModes:
    - ReadOnlyMany  # access mode 
  resources:
    requests:
      storage: 100Gi