apiVersion: v1
kind: Secret
metadata:
    name: az-domain-cert-pemkey
    namespace: opensearch
    labels:
        app/group: corus
type: Opaque
stringData:
    pemkey.pem: |
        -----BEGIN PRIVATE KEY-----
        MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDRhNBewfihlpjI
        FLYjPAhOhxWDNnR6qWyU7X5pIXQ72QYrHlvo2/iM4cH6xJk44TyWg85DpNycqCdo
        dCQGFYYe8HAsO4lmPbjS2GYJ2QzdZyn2Zj2vYq7tJgCdcQnV3AOAsoD4omOqI6vJ
        HDwTLlAxyFoC8fTaAuae7kBnFwuc2xDURgHYHt+fVVQeeJRG7eLG6b60EjV3+8hZ
        JWsRj2wY5Idl55IE0ymF/dvyoEUEYtxC8zwsh2Gt+YW4LRAon9igj9XvJ+MmULU1
        KL8A90pwLwsBAiyjpsZIGZ1AorHyUUu5d3YgkZOb5uNTtIjBmCMhqhwQCiT8oc3K
        83aQNpz5AgMBAAECggEBAM3Nzzv0/vwCyMpohcywcFxqlngP6nR+rbjQXIZ6JQmQ
        kV2TcaaXRFtmeruPmA5mOLSEffy2GToMdsFErAoJ5HfJp/Xa+YkjgcQiaoCr4tYs
        Ouzc2yTHI5qw5JPCcG3QsuQc81DHemyqo1hl0qDosj9kVP5lmyT3Cn/8+egJnA+S
        3MVtoxqc29gQSBizxHBTE/q2D15KmXQN5/sLrxTRYdK84OsE5dX36v0UWGjHVod8
        tpYrpmS/YRqBV4CY0z4kKtwFvu8efoF5q1Me5QSRi2gusaKY1fSkdRfV8upTTCo6
        qEoa5LzNYBDiedfbHFOlPJ4MzYd25QLinMj/ltprYj0CgYEA52eF3BPnUzPMidA0
        okU44HozpQ2egN/Hg5x+DwLKVFA/AW0pgjenuUw0Ze1HR2ma+D18E2D9qUSXhZ1b
        yJZu88a2pD4Zatha/8oiofVbanPTGxENRactAKLeu1rUiGPYIuENUuLZPJCJ1WSn
        V3bym0NR20k8on3cFyG/sQJlk/MCgYEA58nJrXRVTOSBSRxcw2tVhvibo5CQeVG6
        SX9KZ1yIS2msGSI/euDqO4zmDTHR7snCtXJbxQOeR83N+9FwKk1855H9tFCWisnR
        P0JdgDjt2MPiuGG2VKlkkLv5/+SQUZiH82hNgpFYe3Iw2bv8pxkpjFNFG13gOebE
        uoYcQAc/gmMCgYEAtTAe5PKEt2YgqmvnOoO/BC1LENq4GCqgOtIm9jP2HsxyePhz
        fu17G6CqioCexjDPUb46z6WrGIWHquxKeKYpnCEk0zd4iWt83Tn1oiDOgmzMiC3y
        2W4L06qzgbmeHmknTDAxUYwkEsMN2ZOlX9vYHHA6wNv4aTbpRQd84+l/hbcCgYEA
        zlSnbfuHz0n9+HoB7YeHe/2kdmbC5OwmuzRPpFEPlqn7o+gDwDuk5tvXEdnOehUq
        eWDSZj+BT4PZoBdhFJcj3/Pqdu/iAqwC06AdIX4L5BEDqoR4zUZ5GgnrUqpA+hGg
        u8GWdesya7lL2RbpoknY3WxmsSTQ7FoLt8qYLTsGgucCgYACIOEVtHe+h8HoOEeP
        f64E+1b3qwYL8fZgYp7SiHNuSEFU5WZHbjU/Fz7lNj7vo+qQYWU2zEuNZQ61YR4R
        2pZR/c2piAxcICW9n5weDKeF+6kq+X6l8J1vhpTawT1zHUCG8vmzpA/Nw3AhrKOQ
        BXdubtQxCCXXSdlNQWe62tftyw==
        -----END PRIVATE KEY-----

    esnode-key.pem: |
        Bag Attributes
            Microsoft Local Key set: <No Values>
            localKeyID: 01 00 00 00 
            friendlyName: {4B2A7C03-E2D0-401D-8629-2EF95AC19309}
            Microsoft CSP Name: Microsoft Enhanced RSA and AES Cryptographic Provider
        Key Attributes
            X509v3 Key Usage: 10 
        -----BEGIN PRIVATE KEY-----
        MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDRhNBewfihlpjI
        FLYjPAhOhxWDNnR6qWyU7X5pIXQ72QYrHlvo2/iM4cH6xJk44TyWg85DpNycqCdo
        dCQGFYYe8HAsO4lmPbjS2GYJ2QzdZyn2Zj2vYq7tJgCdcQnV3AOAsoD4omOqI6vJ
        HDwTLlAxyFoC8fTaAuae7kBnFwuc2xDURgHYHt+fVVQeeJRG7eLG6b60EjV3+8hZ
        JWsRj2wY5Idl55IE0ymF/dvyoEUEYtxC8zwsh2Gt+YW4LRAon9igj9XvJ+MmULU1
        KL8A90pwLwsBAiyjpsZIGZ1AorHyUUu5d3YgkZOb5uNTtIjBmCMhqhwQCiT8oc3K
        83aQNpz5AgMBAAECggEBAM3Nzzv0/vwCyMpohcywcFxqlngP6nR+rbjQXIZ6JQmQ
        kV2TcaaXRFtmeruPmA5mOLSEffy2GToMdsFErAoJ5HfJp/Xa+YkjgcQiaoCr4tYs
        Ouzc2yTHI5qw5JPCcG3QsuQc81DHemyqo1hl0qDosj9kVP5lmyT3Cn/8+egJnA+S
        3MVtoxqc29gQSBizxHBTE/q2D15KmXQN5/sLrxTRYdK84OsE5dX36v0UWGjHVod8
        tpYrpmS/YRqBV4CY0z4kKtwFvu8efoF5q1Me5QSRi2gusaKY1fSkdRfV8upTTCo6
        qEoa5LzNYBDiedfbHFOlPJ4MzYd25QLinMj/ltprYj0CgYEA52eF3BPnUzPMidA0
        okU44HozpQ2egN/Hg5x+DwLKVFA/AW0pgjenuUw0Ze1HR2ma+D18E2D9qUSXhZ1b
        yJZu88a2pD4Zatha/8oiofVbanPTGxENRactAKLeu1rUiGPYIuENUuLZPJCJ1WSn
        V3bym0NR20k8on3cFyG/sQJlk/MCgYEA58nJrXRVTOSBSRxcw2tVhvibo5CQeVG6
        SX9KZ1yIS2msGSI/euDqO4zmDTHR7snCtXJbxQOeR83N+9FwKk1855H9tFCWisnR
        P0JdgDjt2MPiuGG2VKlkkLv5/+SQUZiH82hNgpFYe3Iw2bv8pxkpjFNFG13gOebE
        uoYcQAc/gmMCgYEAtTAe5PKEt2YgqmvnOoO/BC1LENq4GCqgOtIm9jP2HsxyePhz
        fu17G6CqioCexjDPUb46z6WrGIWHquxKeKYpnCEk0zd4iWt83Tn1oiDOgmzMiC3y
        2W4L06qzgbmeHmknTDAxUYwkEsMN2ZOlX9vYHHA6wNv4aTbpRQd84+l/hbcCgYEA
        zlSnbfuHz0n9+HoB7YeHe/2kdmbC5OwmuzRPpFEPlqn7o+gDwDuk5tvXEdnOehUq
        eWDSZj+BT4PZoBdhFJcj3/Pqdu/iAqwC06AdIX4L5BEDqoR4zUZ5GgnrUqpA+hGg
        u8GWdesya7lL2RbpoknY3WxmsSTQ7FoLt8qYLTsGgucCgYACIOEVtHe+h8HoOEeP
        f64E+1b3qwYL8fZgYp7SiHNuSEFU5WZHbjU/Fz7lNj7vo+qQYWU2zEuNZQ61YR4R
        2pZR/c2piAxcICW9n5weDKeF+6kq+X6l8J1vhpTawT1zHUCG8vmzpA/Nw3AhrKOQ
        BXdubtQxCCXXSdlNQWe62tftyw==
        -----END PRIVATE KEY-----
