apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-master
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  storageClassName: manual
  hostPath:
    path: /volume/redis-master
    # path: "/data/kind_host_volume"
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: redis-replicas
# spec:
#   capacity:
#     storage: 100Gi
#   accessModes:
#     - ReadOnlyMany
#   storageClassName: manual
#   hostPath:
#     path: /volume/redis-replicas
#     # path: "/data/kind_host_volume"
