apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-master
  namespace: redis
spec:
  volumeName: redis-master
  storageClassName: manual
  accessModes:
    - ReadOnlyMany  # access mode 
  resources:
    requests:
      storage: 100Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: redis-replicas
#   namespace: redis
# spec:
#   volumeName: redis-replicas
#   storageClassName: manual
#   accessModes:
#     - ReadOnlyMany  # access mode 
#   resources:
#     requests:
#       storage: 100Gi